# Generated by Django 4.0.5 on 2022-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='total_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
