# Generated by Django 4.0.5 on 2022-07-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0001_initial'),
        ('Submit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='challenge',
        ),
        migrations.AddField(
            model_name='submit',
            name='challenge_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Challenge.challengeelement'),
        ),
    ]
