# Generated by Django 4.0.5 on 2022-07-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submit', '0004_submit_shortest_runtime_delete_submitresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
