# Generated by Django 4.0.5 on 2022-07-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='total_participant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
