# Generated by Django 4.0.5 on 2022-07-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Challenge', '0002_challenge_total_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='total_participant',
        ),
    ]
