# Generated by Django 4.0.5 on 2022-07-10 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sample', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Mid'), (3, 'High')], null=True)),
                ('total_test_case', models.IntegerField(blank=True, default=0, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('quality_assurance', models.BooleanField(blank=True, default=False, null=True)),
                ('character_limit', models.IntegerField(blank=True, default=10000, null=True)),
                ('total_participant', models.IntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('is_private', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assignment.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Input'), (2, 'Output')], null=True)),
                ('data_type', models.IntegerField(blank=True, choices=[(1, 'Integer'), (2, 'Long'), (3, 'Float'), (4, 'Double'), (5, 'Char'), (6, 'String'), (7, 'Boolean'), (8, 'Arrayofintegers'), (9, 'Arrayoflongs'), (10, 'Arrayoffloats'), (11, 'Arrayofdoubles'), (12, 'Arrayofchars'), (13, 'Arrayofstrings'), (14, 'Arrayofbooleans'), (15, 'Matrixofintegers'), (16, 'Matrixoflongs'), (17, 'Matrixoffloats'), (18, 'Matrixofdoubles'), (19, 'Matrixofchars'), (20, 'Matrixofstrings'), (21, 'Matrixofbooleans')], null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assignment.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Parammeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, choices=[(1, 'Input'), (2, 'Output')], null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('data_type', models.IntegerField(blank=True, choices=[(1, 'Integer'), (2, 'Long'), (3, 'Float'), (4, 'Double'), (5, 'Char'), (6, 'String'), (7, 'Boolean'), (8, 'Arrayofintegers'), (9, 'Arrayoflongs'), (10, 'Arrayoffloats'), (11, 'Arrayofdoubles'), (12, 'Arrayofchars'), (13, 'Arrayofstrings'), (14, 'Arrayofbooleans'), (15, 'Matrixofintegers'), (16, 'Matrixoflongs'), (17, 'Matrixoffloats'), (18, 'Matrixofdoubles'), (19, 'Matrixofchars'), (20, 'Matrixofstrings'), (21, 'Matrixofbooleans')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assignment.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit', models.IntegerField(blank=True, default=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assignment.assignment')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assignment.language')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Assignment.assignmenttag'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.account'),
        ),
    ]
