# Generated by Django 4.0.5 on 2022-07-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='image',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
