# Generated by Django 4.0.5 on 2022-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0002_assignment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(1, 'Easy'), (2, 'Mid'), (3, 'High')], null=True),
        ),
    ]
