# Generated by Django 4.0.5 on 2022-07-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0004_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.IntegerField(blank=True, choices=[(1, 'Notrun'), (2, 'Solo')], null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
